services:
    nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/ssl:/etc/nginx/ssl
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/logs:/var/log/nginx
            - ./nginx/data:/data
            - ./nginx/letsencrypt:/etc/letsencrypt
            - ./nginx/certbot:/var/lib/certbot
            - ./nginx/letsencrypt-data:/var/lib/letsencrypt
        